sources:
  analytics-postgres:
    kind: postgres
    host: postgres
    port: 5432
    database: analytics_db
    user: analytics_user
    password: analytics_password

tools:
  test-connection:
    kind: postgres-sql
    source: analytics-postgres
    description: "PostgreSQL接続テスト"
    statement: SELECT 'Hello from PostgreSQL' as message, NOW() as timestamp

  execute-query:
    kind: postgres-execute-sql
    source: analytics-postgres
    description: "動的SQLクエリを実行する"

toolsets:
  analytics-toolset:
    - test-connection
    - execute-query